[env]
CARGO_TARGET_DIR = {value = "target", condition = {env_not_set = ["CARGO_TARGET_DIR"]}}
CARGO_WASM_PATH = "${CARGO_TARGET_DIR}/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm"
CARGO_PROFILE = "dev"
TARGET_DIR = "target"
CARGO_MANIFEST_DIR = "${CARGO_MAKE_WORKING_DIRECTORY}"

[tasks.install-target-wasm32-unknown-unknown]
args = ["target", "install", "wasm32-unknown-unknown"]
command = "rustup"

[tasks.basic-http-server]
install_crate = { crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help" }

[tasks.wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", binary = "wasm-bindgen", test_arg="--help", min_version = "0.2.77" }

[tasks.cargo-build-web]
args = ["build", "--target", "wasm32-unknown-unknown", "--release", "-Zbuild-std=std,panic_abort"]
command = "cargo"
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.cargo-build-web-debug]
args = ["build", "--target", "wasm32-unknown-unknown", "-Zbuild-std=std,panic_abort"]
command = "cargo"
dependencies = ["install-target-wasm32-unknown-unknown"]

[tasks.bindgen]
args = ["--out-dir", "target/", "--out-name", "enc_chat", "--target", "web", "target/wasm32-unknown-unknown/release/enc_chat.wasm"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web", "wasm-bindgen-cli"]

[tasks.bindgen-debug]
args = ["--out-dir", "target/", "--out-name", "enc_chat", "--target", "web", "target/wasm32-unknown-unknown/debug/enc_chat.wasm"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web-debug", "wasm-bindgen-cli"]

[tasks.build-web]
dependencies = ["bindgen"]

[tasks.build-web-debug]
dependencies = ["bindgen-debug"]

[tasks.serve]
args = ["-a", "0.0.0.0:9000"]
command = "basic-http-server"
dependencies = ["build-web", "basic-http-server"]

[tasks.serve-debug]
args = ["-a", "0.0.0.0:9000"]
command = "basic-http-server"
dependencies = ["build-web-debug", "basic-http-server"]
